import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { supabase } from "@/lib/db";
import { callOpenRouter } from "@/lib/ai";

// GET - List all papers generated by the teacher
export async function GET(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== "teacher") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: teacherUser } = await supabase
      .from('users')
      .select('id')
      .eq('email', session.user.email)
      .single();

    if (!teacherUser) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const { data: teacher } = await supabase
      .from('teachers')
      .select('id')
      .eq('user_id', teacherUser.id)
      .single();

    if (!teacher) {
      return NextResponse.json({ error: "Teacher not found" }, { status: 404 });
    }

    const { data: papers, error } = await supabase
      .from('papers')
      .select('*, subject:subjects(name, code), class:classes(name, level)')
      .eq('generated_by_id', teacherUser.id)
      .order('created_at', { ascending: false });

    if (error) {
      throw error;
    }

    return NextResponse.json(papers || []);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// POST - Generate a new paper
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== "teacher") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: teacherUser } = await supabase
      .from('users')
      .select('id')
      .eq('email', session.user.email)
      .single();

    if (!teacherUser) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const { data: teacherRecord } = await supabase
      .from('teachers')
      .select('id')
      .eq('user_id', teacherUser.id)
      .single();

    if (!teacherRecord) {
      return NextResponse.json({ error: "Teacher not found" }, { status: 404 });
    }

    const formData = await request.formData();
    const title = formData.get("title") as string;
    const subjectId = formData.get("subjectId") as string;
    const classId = formData.get("classId") as string;
    const syllabusInfo = formData.get("syllabusInfo") as string;
    const selectedSyllabusTopicIds = formData.get("selectedSyllabusTopicIds") as string;
    const savedFormatId = formData.get("savedFormatId") as string | null;
    const sampleFile = formData.get("sampleFile") as File | null;

    if (!title || !subjectId || !classId || !syllabusInfo) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Validate subject and class belong to teacher
    // Get teacher record first
    const { data: teacher } = await supabase
      .from('teachers')
      .select('id')
      .eq('user_id', teacherUser.id)
      .single();

    if (!teacher) {
      return NextResponse.json({ error: "Teacher not found" }, { status: 404 });
    }

    // Check if subject exists and belongs to the class
    const { data: subject, error: subjectError } = await supabase
      .from('subjects')
      .select('id, name, code, class_id')
      .eq('id', subjectId)
      .single();

    if (subjectError || !subject) {
      return NextResponse.json({ error: "Subject not found" }, { status: 404 });
    }

    // Verify subject belongs to the specified class
    if (subject.class_id !== classId) {
      return NextResponse.json({ error: "Subject does not belong to this class" }, { status: 400 });
    }

    // Check if teacher is assigned to this subject (through teacher_subjects OR direct teacher_id)
    // Method 1: Check if subject has teacher_id set directly
    const { data: subjectWithTeacher } = await supabase
      .from('subjects')
      .select('id, teacher_id')
      .eq('id', subjectId)
      .eq('teacher_id', teacherUser.id)
      .single();

    // Method 2: Check through teacher_subjects table
    const { data: teacherSubject } = await supabase
      .from('teacher_subjects')
      .select('teacher_id, subject_id')
      .eq('teacher_id', teacher.id)
      .eq('subject_id', subjectId)
      .single();

    // Teacher is assigned if either method returns a result
    if (!subjectWithTeacher && !teacherSubject) {
      return NextResponse.json({ error: "You are not assigned to teach this subject/class" }, { status: 403 });
    }

    const subjectName = subject.name;

    const { data: classDoc } = await supabase
      .from('classes')
      .select('name, level')
      .eq('id', classId)
      .single();

    if (!classDoc) {
      return NextResponse.json({ error: "Class not found" }, { status: 404 });
    }

    // Fetch detailed syllabus information if topic IDs provided
    let detailedSyllabusInfo = syllabusInfo;
    if (selectedSyllabusTopicIds) {
      try {
        const topicIds = JSON.parse(selectedSyllabusTopicIds);
        if (Array.isArray(topicIds) && topicIds.length > 0) {
          const { data: syllabusTopics } = await supabase
            .from('syllabus')
            .select('topic, description, term, is_completed')
            .in('id', topicIds);

          if (syllabusTopics && syllabusTopics.length > 0) {
            // Create detailed syllabus description
            const topicsByTerm = syllabusTopics.reduce((acc: any, topic: any) => {
              if (!acc[topic.term]) acc[topic.term] = [];
              acc[topic.term].push(topic);
              return acc;
            }, {});

            detailedSyllabusInfo = Object.entries(topicsByTerm)
              .map(([term, topics]: [string, any]) => {
                const termName = term === 'final' ? 'Final Term' : term.toUpperCase().replace('TERM', 'Term ');
                const topicList = topics.map((t: any) => 
                  `- ${t.topic}${t.description ? ` (${t.description})` : ''}${t.is_completed ? ' [Completed]' : ''}`
                ).join('\n');
                return `${termName}:\n${topicList}`;
              })
              .join('\n\n');
          }
        }
      } catch (error) {
        console.error("Error parsing syllabus topic IDs:", error);
      }
    }

    // Process sample file or saved format
    let samplePaperUrl = "";
    let samplePaperText = "";
    
    // If saved format is selected, use that instead of uploaded file
    if (savedFormatId) {
      const { data: savedPaper } = await supabase
        .from('papers')
        .select('sample_paper_url, generated_content')
        .eq('id', savedFormatId)
        .eq('generated_by_id', teacherUser.id)
        .single();

      if (savedPaper && savedPaper.sample_paper_url) {
        samplePaperUrl = savedPaper.sample_paper_url;
        // Extract text from saved format if possible
        if (savedPaper.generated_content) {
          samplePaperText = `[SAVED_FORMAT_PAPER] - Use the following paper format as reference:\n\n${savedPaper.generated_content.substring(0, 2000)}...\n\nAnalyze the structure, format, layout, title placement, subtitle style, subject header, question numbering, marking scheme format, and overall design from this saved format.`;
        } else {
          samplePaperText = "[SAVED_FORMAT_PAPER] - A saved paper format has been selected. Analyze its structure, format, layout, title placement, subtitle style, subject header, question numbering, marking scheme format, and overall design, then replicate it exactly.";
        }
      }
    } else if (sampleFile) {
      const bytes = await sampleFile.arrayBuffer();
      const buffer = Buffer.from(bytes);
      const base64 = buffer.toString("base64");
      const mimeType = sampleFile.type;
      samplePaperUrl = `data:${mimeType};base64,${base64}`;
      
      // Extract text from file
      if (sampleFile.type === "text/plain" || sampleFile.name?.endsWith(".txt")) {
        samplePaperText = buffer.toString("utf-8");
      } else if (sampleFile.type === "application/pdf" || sampleFile.name?.endsWith(".pdf")) {
        // For PDF, try to extract text (basic approach - in production use pdf-parse library)
        // For now, we'll indicate PDF was provided and AI should analyze structure
        samplePaperText = "[PDF_SAMPLE_PAPER_PROVIDED] - The uploaded file is a PDF format sample paper. Analyze its structure, format, layout, and design elements.";
      } else if (
        sampleFile.type === "application/msword" || 
        sampleFile.type === "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ||
        sampleFile.name?.endsWith(".doc") || 
        sampleFile.name?.endsWith(".docx")
      ) {
        // For Word documents, try to extract text
        // Basic approach: try to read as text (works for some docx files)
        try {
          samplePaperText = buffer.toString("utf-8");
          // If it's mostly binary, indicate it's a Word doc
          if (samplePaperText.length < 100 || samplePaperText.includes("\x00")) {
            samplePaperText = "[DOCX_SAMPLE_PAPER_PROVIDED] - The uploaded file is a Word document sample paper. Analyze its structure, format, layout, title placement, subtitle style, subject header, question numbering, marking scheme format, and overall design.";
          }
        } catch (e) {
          samplePaperText = "[DOCX_SAMPLE_PAPER_PROVIDED] - The uploaded file is a Word document sample paper. Analyze its structure, format, layout, title placement, subtitle style, subject header, question numbering, marking scheme format, and overall design.";
        }
      }
    }

    // Generate paper using AI with Punjab Board 2025 curriculum focus
    const systemPrompt = `You are an expert teacher creating exam papers for Punjab Board curriculum 2025. You specialize in generating high-quality exam papers that strictly follow Punjab Board standards, format, and assessment patterns. When a sample paper or saved format is provided, you must perform deep analysis of its design, structure, formatting, and style, then replicate it EXACTLY. Always generate questions based on the provided syllabus topics.`;
    
    const prompt = `Generate an exam paper for Punjab Board curriculum 2025 based on the following requirements:

SUBJECT: ${subjectName}
CLASS: ${classDoc.name} (Level ${classDoc.level})

SYLLABUS TOPICS TO COVER:
${detailedSyllabusInfo}

IMPORTANT: Generate questions ONLY from the syllabus topics listed above. Ensure all questions are directly related to these topics and follow Punjab Board 2025 curriculum standards.

${samplePaperText ? `=== SAMPLE PAPER PROVIDED - ANALYZE DEEPLY ===
${samplePaperText}

CRITICAL FORMAT ANALYSIS - REPLICATE EXACTLY:

1. HEADER STRUCTURE (MUST MATCH EXACTLY):
   - School name format: "ALIGARH PUBLIC SCHOOL GULBERG, LAHORE" (centered, bold, uppercase)
   - Exam details on right: "Send Ups, 2025" and "Paper code:XXXX" format
   - Left side alignment: "Subject: [Subject Name]", "Paper: [Objective/Subjective]", "Max. Marks: [Number]"
   - Right side alignment: "Class: [Class]", "Section: [Sections]", "Time Allowed: [Time]"
   - Exact spacing and alignment as shown in sample

2. QUESTION FORMAT (MUST MATCH EXACTLY):
   - For MCQs: "Q. 1. MCQs. Choose the most appropriate answer." followed by total marks in parentheses
   - Question numbering: Simple numbers (1, 2, 3, etc.)
   - Options format: (A), (B), (C), (D) in parentheses, bold
   - Options alignment: Horizontal or as shown in sample
   
   - For Short Answers: "Q. 2. Write short answers to any five (5) questions." followed by "(5×2=10)" format
   - For Long Questions: "Long Questions. Attempt any two questions." followed by "(2 X 9= 18)" format
   - Sub-parts: (a) and (b) with individual marks shown
   - Marking scheme: Show marks for each question/sub-part

3. SECTION ORGANIZATION (MUST FOLLOW EXACTLY):
   - Q. 1: MCQs section - 12 questions, students answer all 12 (12 marks total)
   - Q. 2: Short answers - 8 questions provided, students answer any 5 (5×2=10 marks)
   - Q. 3: Short answers - 8 questions provided, students answer any 5 (5×2=10 marks)
   - Q. 4, Q. 5, Q. 6: Long questions - 3 questions provided, each with (a) and (b) parts
     * Each question: (a) = 4 marks, (b) = 5 marks, total = 9 marks per question
     * Students answer any 2 questions (2 × 9 = 18 marks)
   - Total marks: 12 + 10 + 10 + 18 = 50 marks (or as per sample)
   - If sample has "Part 1" or sections, replicate exactly
   - If sample has separate pages for Objective and Subjective, maintain that structure

4. EXACT REPLICATION REQUIREMENTS:
   - Same header layout and alignment
   - Same question numbering style
   - Same option format (A), (B), (C), (D)
   - Same marking scheme format (e.g., "5×2=10", "2 X 9= 18")
   - Same section headers and organization
   - Same overall spacing and formatting
   - Same font style indicators (bold for headers, etc.)

5. CONTENT GENERATION (MUST FOLLOW THIS STRUCTURE):
   - Q. 1: Generate exactly 12 MCQs based on the syllabus topics provided above
   - Q. 2: Generate exactly 8 short answer questions (students answer any 5) covering the syllabus topics
   - Q. 3: Generate exactly 8 short answer questions (students answer any 5) covering the syllabus topics
   - Q. 4, Q. 5, Q. 6: Generate exactly 3 long questions, each with:
     * Part (a): 4 marks question
     * Part (b): 5 marks question
     * Total: 9 marks per question (students answer any 2)
   - All questions MUST be based ONLY on the syllabus topics listed above
   - All questions must align with Punjab Board 2025 curriculum
   - Maintain same difficulty level as sample (if provided)
   - Distribute questions across all syllabus topics to ensure comprehensive coverage

IMPORTANT: The format, layout, structure, and design must be IDENTICAL to the sample. Only the question content should be new, based on the syllabus provided.` : `=== PUNJAB BOARD 2025 STANDARD FORMAT ===

Generate paper with this structure:

HEADER FORMAT:
[School Name] (centered, bold, uppercase)
[Exam Name, Year]                    [Paper code:XXXX]
Subject: [Subject]                   Class: [Class]
Paper: [Objective/Subjective]        Section: [Sections]
Max. Marks: [Number]                 Time Allowed: [Time]

QUESTION SECTIONS (EXACT STRUCTURE REQUIRED):
- Q. 1. MCQs section: 12 questions, students answer all 12 (12 marks total)
- Q. 2. Short answers: Provide 8 questions, students answer any 5 (5×2=10 marks)
- Q. 3. Short answers: Provide 8 questions, students answer any 5 (5×2=10 marks)
- Q. 4, Q. 5, Q. 6. Long Questions: Provide 3 questions, students answer any 2 (2×9=18 marks)
  - Each long question has two parts:
    * (a) = 4 marks
    * (b) = 5 marks
    * Total per question = 9 marks
  - Format: "Q. 4(a) [question text] 4" and "Q. 4(b) [question text] 5"

PUNJAB BOARD 2025 CURRICULUM:
- All questions must align with Punjab Board 2025 curriculum
- Follow Punjab Board assessment patterns
- Use appropriate difficulty for ${classDoc.name} students
- Generate questions ONLY from the syllabus topics provided above
- Ensure comprehensive coverage of all listed syllabus topics`}

SYLLABUS INFORMATION:
The syllabus topics listed above are from the teacher's syllabus management system. Generate questions that:
- Cover ALL the listed syllabus topics comprehensively
- Ensure questions are directly related to the specific topics provided
- Follow Punjab Board 2025 learning outcomes for each topic
- Use Punjab Board standard question formats
- Match the difficulty and style of the sample/saved format (if provided)
- Distribute questions evenly across all syllabus topics to ensure balanced coverage

OUTPUT REQUIREMENTS:
Generate the complete paper text with:
1. Exact header format (matching sample if provided)
2. Proper question sections with EXACT structure:
   - Q. 1: 12 MCQs (all must be answered)
   - Q. 2: 8 short answer questions (answer any 5, 5×2=10 marks)
   - Q. 3: 8 short answer questions (answer any 5, 5×2=10 marks)
   - Q. 4, Q. 5, Q. 6: 3 long questions, each with (a) 4 marks and (b) 5 marks (answer any 2, 2×9=18 marks)
3. Correct numbering and marking scheme
4. All formatting indicators (bold, alignment, etc.) clearly marked
5. Questions based ONLY on the syllabus topics provided above
6. Punjab Board 2025 curriculum alignment
7. Comprehensive coverage of all listed syllabus topics

CRITICAL: The paper MUST have this exact structure:
- Q. 1: 12 MCQs
- Q. 2: 8 short questions (answer any 5)
- Q. 3: 8 short questions (answer any 5)
- Q. 4, Q. 5, Q. 6: 3 long questions with (a) and (b) parts (answer any 2)

Generate the complete paper now, following the EXACT format of the sample (if provided) or Punjab Board 2025 standard format with this structure:`;

    const generatedContent = await callOpenRouter(prompt, systemPrompt);

    // Generate simple text-based document (can be opened in Word)
    const docContent = `EXAM PAPER\n${"=".repeat(50)}\n\n${generatedContent}\n\n${"=".repeat(50)}\nGenerated on: ${new Date().toLocaleString()}`;
    const docBuffer = Buffer.from(docContent, "utf-8");
    const docBase64 = docBuffer.toString("base64");
    const docxFileUrl = `data:text/plain;base64,${docBase64}`;

    // Create paper document
    const { data: paper, error: paperError } = await supabase
      .from('papers')
      .insert([{
        title,
        subject_id: subjectId,
        class_id: classId,
        syllabus_info: syllabusInfo,
        sample_paper_url: samplePaperUrl || null,
        generated_content: generatedContent,
        docx_file_url: docxFileUrl,
        generated_by_id: teacherUser.id,
      }])
      .select()
      .single();

    if (paperError) {
      throw paperError;
    }

    return NextResponse.json({
      success: true,
      paper: {
        _id: paper.id,
        title: paper.title,
        subject: subjectName,
        class: classDoc.name,
        createdAt: paper.created_at,
      },
    });
  } catch (error: any) {
    console.error("Error generating paper:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

