"""
Paper generation and management endpoints
"""

from fastapi import APIRouter, HTTPException, status, Depends, UploadFile, File, Form
from pydantic import BaseModel
from typing import Optional, List
from app.core.auth import require_teacher, CurrentUser
from app.core.database import get_supabase
from app.services.ai_service import generate_exam_paper
import logging
import json

logger = logging.getLogger(__name__)

router = APIRouter()


@router.get("")
async def get_papers(user: CurrentUser = Depends(require_teacher)):
    """Get all papers generated by teacher"""
    try:
        supabase = get_supabase()
        
        # Get teacher record
        teacher_result = supabase.table("teachers").select("id").eq(
            "user_id", user.id
        ).maybe_single().execute()
        
        if not teacher_result.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Teacher not found"
            )
        
        # Get papers
        result = supabase.table("papers").select(
            "*, subject:subjects(name, code), class:classes(name, level)"
        ).eq("generated_by_id", user.id).order("created_at", desc=True).execute()
        
        return result.data or []
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting papers: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get papers: {str(e)}"
        )


@router.post("")
async def create_paper(
    title: str = Form(...),
    subjectId: str = Form(...),
    classId: str = Form(...),
    syllabusInfo: str = Form(...),
    selectedSyllabusTopicIds: str = Form(...),
    savedFormatId: Optional[str] = Form(None),
    sampleFile: Optional[UploadFile] = File(None),
    user: CurrentUser = Depends(require_teacher)
):
    """Generate and save a new paper"""
    try:
        supabase = get_supabase()
        
        # Get teacher record
        teacher_result = supabase.table("teachers").select("id").eq(
            "user_id", user.id
        ).maybe_single().execute()
        
        if not teacher_result.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Teacher not found"
            )
        
        teacher = teacher_result.data
        
        # Verify subject
        subject_result = supabase.table("subjects").select(
            "id, name, code, class_id, teacher_id"
        ).eq("id", subjectId).maybe_single().execute()
        
        if not subject_result.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Subject not found"
            )
        
        subject = subject_result.data
        
        if subject["class_id"] != classId:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Subject does not belong to this class"
            )
        
        # Check teacher assignment
        subject_with_teacher = supabase.table("subjects").select(
            "id, teacher_id"
        ).eq("id", subjectId).eq(
            "teacher_id", user.id
        ).maybe_single().execute()
        
        teacher_subject = supabase.table("teacher_subjects").select(
            "teacher_id, subject_id"
        ).eq("teacher_id", teacher["id"]).eq(
            "subject_id", subjectId
        ).maybe_single().execute()
        
        if not subject_with_teacher.data and not teacher_subject.data:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="You are not assigned to teach this subject/class"
            )
        
        # Get class info
        class_result = supabase.table("classes").select(
            "name, level"
        ).eq("id", classId).maybe_single().execute()
        
        if not class_result.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Class not found"
            )
        
        # Parse syllabus info
        try:
            syllabus_data = json.loads(syllabusInfo)
            topics = [t.get("topic", "") for t in syllabus_data if t.get("selected")]
        except:
            topics = []
        
        # Generate paper using AI
        try:
            paper_data = await generate_exam_paper(
                subject["name"],
                f"Class {class_result.data['level']}",
                "full",  # Default to full paper
                topics,
                100
            )
        except Exception as e:
            logger.error(f"Error generating paper: {str(e)}")
            paper_data = {"questions": [], "answerKey": ""}
        
        # Save paper
        paper = supabase.table("papers").insert({
            "title": title,
            "subject_id": subjectId,
            "class_id": classId,
            "content": json.dumps(paper_data),
            "generated_by_id": user.id,
            "format_id": savedFormatId
        }).select().single().execute()
        
        if not paper.data:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to save paper"
            )
        
        return paper.data
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error creating paper: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create paper: {str(e)}"
        )


@router.get("/{paper_id}/download")
async def download_paper(
    paper_id: str,
    user: CurrentUser = Depends(require_teacher)
):
    """Download paper (returns paper data)"""
    try:
        supabase = get_supabase()
        
        # Get paper
        paper_result = supabase.table("papers").select(
            "*, subject:subjects(name, code), class:classes(name, level)"
        ).eq("id", paper_id).eq("generated_by_id", user.id).maybe_single().execute()
        
        if not paper_result.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Paper not found"
            )
        
        return paper_result.data
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading paper: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to download paper: {str(e)}"
        )

